#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
  entities:
    Category:
      class: App\Entity\Category
      list:
        fields:
          - { property: 'idCategory', label: 'Id' }
          - { property: 'name', label: 'Name' }
          - { property: 'summary', label: 'Summary' }
      form:
        fields:
          - { property: 'name'}
          - { property: 'summary'}