#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
#        - App\Entity\Order
easy_admin:
  entities:
    Category:
      class: App\Entity\Category
      list:
        fields:
          - { property: 'idCategory', label: 'Id' }
          - { property: 'name', label: 'Name' }
          - { property: 'summary', label: 'Summary' }
          - { property: 'picture', type: 'image', base_path: '%app.path.category_pictures%' }
      form:
        fields:
          - { property: 'name' }
          - { property: 'summary' }
          - { property: 'pictureFile', type: Vich\UploaderBundle\Form\Type\VichImageType }

