vich_uploader:
    db_driver: orm
    mappings:
        category_pictures:
            uri_prefix: '%app.path.category_pictures%'
            upload_destination: '%kernel.project_dir%/public%app.path.category_pictures%'
            namer: vich_uploader.namer_uniqid

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
